const BUY_PIPELINE=['New Relationship','Diligence Call Complete','NDA Signed + Thesis Captured','Relevant Deal Identified','Interest Meeting Held','Buyer Interest Confirmed','Engagement Active','Closed'];
const SELL_PIPELINE=['New Relationship','Diligence Call Complete','NDA Signed + Buy-Side Thesis Shared','Opportunity Received','Initial Interest Identified','Buy-Side Interest Confirmed','Engagement Active','Closed'];
let pipelineSide='Buy Side';

function installPipelineUI(){
  const metrics=$('metrics');
  if(metrics&&!$('relationshipPipelinePanel')) metrics.insertAdjacentHTML('afterend',`<section id="relationshipPipelinePanel" class="panel relationshipPipeline"><div class="pipelineTop"><div><h2>Opportunity Pipeline</h2><p>Advance each relationship through the buy-side or sell-side process.</p></div><div class="pipelineTabs"><button type="button" class="pipelineTab active" data-pipeline-side="Buy Side">Buy Side</button><button type="button" class="pipelineTab" data-pipeline-side="Sell Side">Sell Side</button></div></div><div class="pipelineScroll"><div id="relationshipPipeline" class="pipelineBoard"></div></div></section>`);
  if(!$('pipelineModal')) document.body.insertAdjacentHTML('beforeend',`<div id="pipelineModal" class="modal hidden"><div class="modalCard small"><div class="modalHead"><div><div class="eyebrow">RELATIONSHIP PIPELINE</div><h2 id="pipelineModalTitle">Update Pipeline</h2></div><button id="closePipelineModal" class="iconBtn" type="button">×</button></div><form id="pipelineForm" class="form"><input id="pipelinePersonId" type="hidden"><p class="modalNote">Move this person forward as the relationship progresses. You can also jump to any stage when needed.</p><div class="pipelineCurrent">Current stage: <strong id="pipelineCurrentStage"></strong></div><div class="formGrid"><label class="span2">Pipeline Stage<select id="pipelineStageInput"></select></label><label id="pipelineDealSizeWrap" class="span2 conditionalField hidden">Interested Deal Size<input id="pipelineDealSizeInput" placeholder="$25M, $100M, etc."></label><label id="pipelineOpportunityWrap" class="span2 conditionalField hidden">Opportunity Drawing Interest<input id="pipelineOpportunityInput" placeholder="Name the opportunity or deal"></label></div><div class="pipelineQuick"><button id="pipelineNextStageBtn" class="nextStageBtn" type="button">Select Next Stage</button><span class="hint">Changes are shared with the team immediately.</span></div><div class="modalActions"><button id="cancelPipeline" type="button" class="ghost">Cancel</button><button class="primary" type="submit">Save Pipeline</button></div></form></div></div>`);
  if(!$('taskModal')) document.body.insertAdjacentHTML('beforeend',`<div id="taskModal" class="modal hidden"><div class="modalCard small"><div class="modalHead"><div><div class="eyebrow">NEXT STEP</div><h2 id="taskModalTitle">Add Next Step</h2></div><button id="closeTaskModal" class="iconBtn" type="button">×</button></div><form id="taskForm" class="form"><input id="taskPersonId" type="hidden"><div class="formGrid"><label class="span2">What needs to happen next?<textarea id="taskActionInput" rows="3" required placeholder="Example: Send NDA and schedule thesis call"></textarea></label><label>Action Owner<input id="taskOwnerInput" placeholder="Chase, Tengku, Peter..."></label><label>Due Date<input id="taskDueInput" type="date"></label></div><div class="modalActions"><button id="cancelTask" type="button" class="ghost">Cancel</button><button class="primary" type="submit">Add Next Step</button></div></form></div></div>`);
}
installPipelineUI();

function stagesForPerson(p,sideOverride){const side=sideOverride||(p?.side==='Buy Side'?'Buy Side':p?.side==='Sell Side'?'Sell Side':pipelineSide);return side==='Buy Side'?BUY_PIPELINE:SELL_PIPELINE}
function normalizedStage(p,sideOverride){const stages=stagesForPerson(p,sideOverride);return stages.includes(p?.pipelineStage)?p.pipelineStage:stages[0]}
function mapTask(r){return{id:r.id,personId:r.person_id,opportunityId:r.opportunity_id,action:r.action||'',owner:r.owner_name||'',dueDate:r.due_date||'',completed:!!r.completed,createdAt:r.created_at,updatedAt:r.updated_at}}
mapPerson=function(r){return{id:r.id,name:r.name,type:r.relationship_type,side:r.primary_side,thesis:r.thesis||'',hasLinkedIn:r.has_linkedin,notes:r.notes||'',pipelineStage:r.pipeline_stage||'New Relationship',interestDealSize:r.interest_deal_size||'',interestOpportunity:r.interest_opportunity||''}}
loadData=async function(){const [p,o,t]=await Promise.all([sb.from('people').select('*').order('created_at'),sb.from('opportunities').select('*').order('updated_at',{ascending:false}),sb.from('tasks').select('*').order('created_at',{ascending:false})]);if(p.error||o.error||t.error){console.error(p.error||o.error||t.error);return}state.people=p.data.map(mapPerson);state.opportunities=o.data.map(mapOpp);state.tasks=t.data.map(mapTask);renderAll()}
subscribe=function(){sb.channel('outerhaven-live').on('postgres_changes',{event:'*',schema:'public',table:'people'},loadData).on('postgres_changes',{event:'*',schema:'public',table:'opportunities'},loadData).on('postgres_changes',{event:'*',schema:'public',table:'tasks'},loadData).subscribe()}

function peopleForPipeline(side){const role=$('roleFilter').value;return state.people.filter(p=>(p.side===side||p.side==='Both')&&(role==='All'||role===side))}
function activeTasks(){const role=$('roleFilter').value;return (state.tasks||[]).filter(t=>!t.completed).filter(t=>{const p=person(t.personId);return p&&(role==='All'||p.side===role||p.side==='Both')}).sort((a,b)=>{if(a.dueDate&&!b.dueDate)return-1;if(!a.dueDate&&b.dueDate)return 1;if(a.dueDate&&b.dueDate)return a.dueDate.localeCompare(b.dueDate);return(b.createdAt||'').localeCompare(a.createdAt||'')})}
function latestTaskForPerson(personId){return (state.tasks||[]).filter(t=>t.personId===personId&&!t.completed).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''))[0]||null}
function renderPipeline(){const board=$('relationshipPipeline');if(!board)return;const stages=pipelineSide==='Buy Side'?BUY_PIPELINE:SELL_PIPELINE,people=peopleForPipeline(pipelineSide);board.innerHTML=stages.map(stage=>{const ps=people.filter(p=>normalizedStage(p,pipelineSide)===stage);return`<section class="pipelineStage"><div class="pipelineStageHead"><div class="pipelineStageName">${esc(stage)}</div><div class="pipelineStageCount">${ps.length}</div></div>${ps.length?ps.map(p=>{const task=latestTaskForPerson(p.id);return`<article class="pipelinePerson" data-pipeline-person="${p.id}"><div class="pipelinePersonName">${esc(p.name)}</div><div class="pipelinePersonMeta">${esc(p.type||p.side||'Relationship')}</div>${task?`<div class="pipelineNextStep"><div class="pipelineNextStepLabel">NEXT STEP</div><div class="pipelineNextStepText">${esc(task.action)}</div><div class="pipelineNextStepMeta">${esc(task.owner||'Unassigned')}${task.dueDate?` · ${esc(fmtDate(task.dueDate))}`:''}</div></div>`:''}${p.interestDealSize?`<div class="pipelineDetail">Deal size: ${esc(p.interestDealSize)}</div>`:''}${p.interestOpportunity?`<div class="pipelineDetail">Opportunity: ${esc(p.interestOpportunity)}</div>`:''}<div class="pipelinePersonActions"><button type="button" class="miniAction" data-add-task="${p.id}">+ Next Step</button></div></article>`}).join(''):'<div class="pipelineEmpty">No relationships here.</div>'}</section>`}).join('');document.querySelectorAll('.pipelineTab').forEach(b=>b.classList.toggle('active',b.dataset.pipelineSide===pipelineSide));bindPipelineActions()}
function bindPipelineActions(){document.querySelectorAll('[data-pipeline-person]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-add-task]'))return;openPipelineModal(el.dataset.pipelinePerson)});document.querySelectorAll('[data-add-task]').forEach(el=>el.onclick=e=>{e.stopPropagation();openTaskModal(el.dataset.addTask)})}

renderDashboard=function(){renderMetrics();renderPipeline();const d=roleData();$('dashOps').innerHTML=d.length?d.slice(0,7).map(o=>`<div class="compactRow"><div><div class="compactTitle">${esc(o.company)}</div><div class="compactMeta">${esc(contactName(o.contactId))} · ${esc(o.side)}</div></div><div class="compactCell">${esc(o.stage)}</div><div class="compactCell">${esc(o.owner||'Unassigned')}</div><div class="compactCell">${esc(o.next||'No next step')}</div><button class="openLink" data-open="${o.id}">Open</button></div>`).join(''):'<div class="compactMeta">No opportunities.</div>';const taskActions=activeTasks().map(t=>({kind:'task',person:person(t.personId),copy:t.action,owner:t.owner||'Unassigned',due:t.dueDate,priority:'Task'}));const oppActions=d.filter(o=>o.next).map(o=>({kind:'opp',person:person(o.contactId),copy:o.next,owner:o.nextOwner||o.owner||'Unassigned',due:o.dueDate,priority:o.priority}));const actions=[...taskActions,...oppActions].slice(0,7);$('dashNext').innerHTML=actions.length?actions.map(a=>`<div class="actionItem"><div class="actionTop"><div class="actionCompany">${esc(a.person?.name||'Unassigned')}</div>${a.kind==='task'?'<span class="taskTag">Person Next Step</span>':badge(a.priority)}</div><div class="actionCopy">${esc(a.copy)}</div><div class="actionMeta">${esc(a.owner)} · ${esc(fmtDate(a.due))}</div></div>`).join(''):'<div class="compactMeta">No next actions.</div>';const mx=Math.max(1,...STAGES.map(s=>d.filter(o=>o.stage===s).length));$('stageSummary').innerHTML=STAGES.map(s=>{const c=d.filter(o=>o.stage===s).length;return`<div class="stageBox"><div class="stageName">${esc(s)}</div><div class="stageCount">${c}</div><div class="stageBar"><div class="stageFill" style="width:${Math.round(c/mx*100)}%"></div></div></div>`}).join('');bindOpen()}

renderNext=function(){const tasks=activeTasks(),opps=roleData().filter(o=>o.next);const taskHtml=tasks.map(t=>{const p=person(t.personId);return`<article class="taskRow"><div><h3>${esc(p?.name||'Unassigned')}</h3><p>${esc(p?.side||'Relationship')} · Person next step</p></div><div class="nextMain">${esc(t.action)}</div><div class="nextMeta2"><strong>${esc(t.owner||'Unassigned')}</strong><br>Action owner</div><div class="nextMeta2"><strong>${esc(fmtDate(t.dueDate))}</strong><br>Due date</div><button class="taskDone" data-complete-task="${t.id}" type="button">Mark Done</button></article>`}).join('');const oppHtml=opps.map(o=>`<article class="nextRow"><div><h3>${esc(contactName(o.contactId))}</h3><p>${esc(o.company)} · ${esc(o.side)}</p></div><div class="nextMain">${esc(o.next)}</div><div class="nextMeta2"><strong>${esc(o.nextOwner||o.owner||'Unassigned')}</strong><br>Action owner</div><div class="nextMeta2"><strong>${esc(fmtDate(o.dueDate))}</strong><br>Due date</div><button class="ghost" data-open="${o.id}">Open</button></article>`).join('');$('nextBoard').innerHTML=taskHtml+oppHtml||'<div class="panel empty">No next steps.</div>';document.querySelectorAll('[data-complete-task]').forEach(b=>b.onclick=()=>completeTask(b.dataset.completeTask));bindOpen()}

renderPeople=function(){const role=$('roleFilter').value,people=state.people.filter(p=>role==='All'||p.side===role||p.side==='Both');$('peopleGrid').innerHTML=people.map(p=>{const ops=state.opportunities.filter(o=>o.contactId===p.id),stage=normalizedStage(p);return`<article class="personCard"><div class="personTop"><div><div class="personName">${esc(p.name)}</div><div class="cardSub">${esc(p.type||'Relationship not specified')} · ${esc(p.side||'')}</div><div class="personStage">${esc(stage)}</div></div><label class="linkedinCheck"><input type="checkbox" data-linkedin="${p.id}" ${p.hasLinkedIn?'checked':''}> LinkedIn access</label></div>${p.interestDealSize?`<div class="personSection"><label>INTERESTED DEAL SIZE</label><div class="nextBox"><div class="nextCopy">${esc(p.interestDealSize)}</div></div></div>`:''}${p.interestOpportunity?`<div class="personSection"><label>OPPORTUNITY DRAWING INTEREST</label><div class="nextBox"><div class="nextCopy">${esc(p.interestOpportunity)}</div></div></div>`:''}<div class="personSection"><label>THESIS</label><textarea data-thesis="${p.id}">${esc(p.thesis)}</textarea></div><div class="personOps">${ops.length?ops.map(o=>`<div class="miniOp"><div><strong>${esc(o.company)}</strong><br><span>${esc(o.stage)}</span></div><button class="openLink" data-open="${o.id}">Open</button></div>`).join(''):'<div class="compactMeta">No opportunities attached yet.</div>'}</div><div class="personButtons"><button class="ghost" type="button" data-update-pipeline="${p.id}">Update Pipeline</button><button class="ghost" type="button" data-add-task="${p.id}">+ Next Step</button><button class="ghost" type="button" data-edit-person="${p.id}">Edit Person</button></div></article>`}).join('');document.querySelectorAll('[data-linkedin]').forEach(x=>x.onchange=async()=>{await sb.from('people').update({has_linkedin:x.checked}).eq('id',x.dataset.linkedin);await loadData()});document.querySelectorAll('[data-thesis]').forEach(x=>x.onchange=async()=>{await sb.from('people').update({thesis:x.value}).eq('id',x.dataset.thesis)});document.querySelectorAll('[data-edit-person]').forEach(x=>x.onclick=()=>openPersonModal(x.dataset.editPerson));document.querySelectorAll('[data-update-pipeline]').forEach(x=>x.onclick=()=>openPipelineModal(x.dataset.updatePipeline));document.querySelectorAll('[data-add-task]').forEach(x=>x.onclick=e=>{e.stopPropagation();openTaskModal(x.dataset.addTask)});bindOpen()}

renderAll=function(){const role=$('roleFilter').value;if(role==='Buy Side'||role==='Sell Side')pipelineSide=role;const taskCount=activeTasks().length;$('navOps').textContent=roleData().length;$('navNext').textContent=roleData().filter(o=>o.next).length+taskCount;$('navPeople').textContent=state.people.filter(p=>role==='All'||p.side===role||p.side==='Both').length;populateFilters();renderDashboard();renderOps();renderNext();renderPeople()}

function openPipelineModal(id){const p=person(id);if(!p)return;const side=p.side==='Buy Side'?'Buy Side':p.side==='Sell Side'?'Sell Side':pipelineSide;pipelineSide=side;const stages=stagesForPerson(p,side),current=normalizedStage(p,side);$('pipelinePersonId').value=p.id;$('pipelineModalTitle').textContent=p.name;$('pipelineCurrentStage').textContent=current;$('pipelineStageInput').innerHTML=stages.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('pipelineStageInput').value=current;$('pipelineDealSizeInput').value=p.interestDealSize||'';$('pipelineOpportunityInput').value=p.interestOpportunity||'';$('pipelineStageInput').dataset.side=side;togglePipelineFields();$('pipelineModal').classList.remove('hidden')}
function togglePipelineFields(){const side=$('pipelineStageInput').dataset.side,stage=$('pipelineStageInput').value,stages=side==='Buy Side'?BUY_PIPELINE:SELL_PIPELINE,index=stages.indexOf(stage);$('pipelineDealSizeWrap').classList.toggle('hidden',!(side==='Buy Side'&&index>=5));$('pipelineOpportunityWrap').classList.toggle('hidden',!(side==='Sell Side'&&index>=4))}
function selectNextPipelineStage(){const side=$('pipelineStageInput').dataset.side,stages=side==='Buy Side'?BUY_PIPELINE:SELL_PIPELINE,i=stages.indexOf($('pipelineStageInput').value);if(i>=0&&i<stages.length-1){$('pipelineStageInput').value=stages[i+1];togglePipelineFields()}}
async function savePipeline(e){e.preventDefault();const id=$('pipelinePersonId').value,stage=$('pipelineStageInput').value,payload={pipeline_stage:stage,interest_deal_size:$('pipelineDealSizeInput').value.trim()||null,interest_opportunity:$('pipelineOpportunityInput').value.trim()||null};const {error}=await sb.from('people').update(payload).eq('id',id);if(error){alert(error.message);return}$('pipelineModal').classList.add('hidden');await loadData()}
function openTaskModal(id){const p=person(id);if(!p)return;$('taskForm').reset();$('taskPersonId').value=p.id;$('taskModalTitle').textContent=`Next Step · ${p.name}`;$('taskOwnerInput').value=currentUser?.email?.startsWith('tengku')?'Tengku':'Chase';$('taskModal').classList.remove('hidden')}
async function saveTask(e){e.preventDefault();const payload={person_id:$('taskPersonId').value,action:$('taskActionInput').value.trim(),owner_name:$('taskOwnerInput').value.trim()||null,due_date:$('taskDueInput').value||null,created_by:currentUser?.id||null};const {error}=await sb.from('tasks').insert(payload);if(error){alert(error.message);return}$('taskModal').classList.add('hidden');await loadData()}
async function completeTask(id){const {error}=await sb.from('tasks').update({completed:true}).eq('id',id);if(error){alert(error.message);return}await loadData()}

document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.pipelineTab').forEach(b=>b.onclick=()=>{pipelineSide=b.dataset.pipelineSide;renderPipeline()});
  $('pipelineStageInput').onchange=togglePipelineFields;
  $('pipelineNextStageBtn').onclick=selectNextPipelineStage;
  $('pipelineForm').onsubmit=savePipeline;
  $('closePipelineModal').onclick=()=>$('pipelineModal').classList.add('hidden');
  $('cancelPipeline').onclick=()=>$('pipelineModal').classList.add('hidden');
  $('taskForm').onsubmit=saveTask;
  $('closeTaskModal').onclick=()=>$('taskModal').classList.add('hidden');
  $('cancelTask').onclick=()=>$('taskModal').classList.add('hidden');
  if($('signUpBtn'))$('signUpBtn').onclick=()=>location.href='/create-account.html';
});