const SUPABASE_URL='https://nfcysxqdwpdhrdpgxrlo.supabase.co';
const SUPABASE_KEY='sb_publishable_nBRZvesX4tz7zUPq5QLYfQ__in76dF5';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const STAGES=['New','Qualifying','Diligence','Engagement','Matching','Introductions','In Discussion'];
let state={people:[],opportunities:[]},selectedId=null,currentUser=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const person=id=>state.people.find(p=>p.id===id);
const contactName=id=>person(id)?.name||'Unassigned';
const badge=v=>`<span class="badge">${esc(v)}</span>`;
const dot=v=>`<span class="dot ${String(v).toLowerCase()}"></span>`;
function fmtDate(v){if(!v)return'No due date';return new Date(v+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function fmtDT(v){if(!v)return'';return new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function mapPerson(r){return{id:r.id,name:r.name,type:r.relationship_type,side:r.primary_side,thesis:r.thesis||'',hasLinkedIn:r.has_linkedin,notes:r.notes||''}}
function mapOpp(r){return{id:r.id,contactId:r.person_id,company:r.title,side:r.side,owner:r.owner_name||'',stage:r.stage,priority:r.priority,size:r.opportunity_size||'',sector:r.sector||'',next:r.next_step||'',nextOwner:r.next_step_owner||'',dueDate:r.due_date||'',notes:r.notes||'',createdAt:r.created_at,updatedAt:r.updated_at}}
async function allowed(email){const {data,error}=await sb.rpc('is_dashboard_email_allowed',{input_email:email});return !error&&data===true}
async function loadData(){const [p,o]=await Promise.all([sb.from('people').select('*').order('created_at'),sb.from('opportunities').select('*').order('updated_at',{ascending:false})]);if(p.error||o.error){console.error(p.error||o.error);return}state.people=p.data.map(mapPerson);state.opportunities=o.data.map(mapOpp);renderAll()}
function roleData(){const r=$('roleFilter').value;return state.opportunities.filter(o=>r==='All'||o.side===r)}
function renderMetrics(){const d=roleData(),m=[['Active Opportunities',d.length,'Across the current view'],['Sell Side',d.filter(o=>o.side==='Sell Side').length,'Raises and sell-side relationships'],['Buy Side',d.filter(o=>o.side==='Buy Side').length,'Buyers and mandates'],['LinkedIn Access',state.people.filter(p=>p.hasLinkedIn).length+'/'+state.people.length,'People with account access']];$('metrics').innerHTML=m.map(x=>`<article class="metric"><div class="metricLabel">${x[0]}</div><div class="metricValue">${x[1]}</div><div class="metricFoot">${x[2]}</div></article>`).join('')}
function renderDashboard(){renderMetrics();const d=roleData();$('dashOps').innerHTML=d.length?d.slice(0,7).map(o=>`<div class="compactRow"><div><div class="compactTitle">${esc(o.company)}</div><div class="compactMeta">${esc(contactName(o.contactId))} · ${esc(o.side)}</div></div><div class="compactCell">${esc(o.stage)}</div><div class="compactCell">${esc(o.owner||'Unassigned')}</div><div class="compactCell">${esc(o.next||'No next step')}</div><button class="openLink" data-open="${o.id}">Open</button></div>`).join(''):'<div class="compactMeta">No opportunities.</div>';$('dashNext').innerHTML=d.filter(o=>o.next).slice(0,7).map(o=>`<div class="actionItem"><div class="actionTop"><div class="actionCompany">${esc(contactName(o.contactId))}</div>${badge(o.priority)}</div><div class="actionCopy">${esc(o.next)}</div><div class="actionMeta">${esc(o.nextOwner||o.owner||'Unassigned')} · ${esc(fmtDate(o.dueDate))}</div></div>`).join('');const mx=Math.max(1,...STAGES.map(s=>d.filter(o=>o.stage===s).length));$('stageSummary').innerHTML=STAGES.map(s=>{const c=d.filter(o=>o.stage===s).length;return`<div class="stageBox"><div class="stageName">${s}</div><div class="stageCount">${c}</div><div class="stageBar"><div class="stageFill" style="width:${Math.round(c/mx*100)}%"></div></div></div>`}).join('');bindOpen()}
function populateFilters(){const owners=[...new Set(state.opportunities.map(o=>o.owner).filter(Boolean))].sort();$('stageFilter').innerHTML='<option value="All">All</option>'+STAGES.map(s=>`<option>${s}</option>`).join('');$('ownerFilter').innerHTML='<option value="All">All</option>'+owners.map(o=>`<option>${esc(o)}</option>`).join('')}
function filtered(){const q=$('searchInput').value.toLowerCase(),s=$('sideFilter').value,st=$('stageFilter').value,ow=$('ownerFilter').value,pr=$('priorityFilter').value,r=$('roleFilter').value;return state.opportunities.filter(o=>[o.company,contactName(o.contactId),o.side,o.owner,o.stage,o.size,o.sector,o.next,o.notes].join(' ').toLowerCase().includes(q)&&(s==='All'||o.side===s)&&(st==='All'||o.stage===st)&&(ow==='All'||o.owner===ow)&&(pr==='All'||o.priority===pr)&&(r==='All'||o.side===r))}
function renderOps(){const d=filtered();$('resultCount').textContent=`${d.length} opportunit${d.length===1?'y':'ies'}`;$('opCards').innerHTML=d.map(o=>`<article class="opCard" data-open="${o.id}"><div class="cardTop"><div><div class="titleRow">${dot(o.priority)}<div class="cardTitle">${esc(o.company)}</div>${badge(o.side)}${badge(o.stage)}</div><div class="cardSub">${esc(contactName(o.contactId))} · ${esc(o.size||'Size not specified')} · ${esc(o.sector||'Type not specified')}</div></div>${badge(o.priority)}</div><div class="nextBox"><div class="nextLabel">NEXT STEP</div><div class="nextCopy">${esc(o.next||'No next step assigned')}</div><div class="nextMeta">${esc(o.nextOwner||o.owner||'Unassigned')} · ${esc(fmtDate(o.dueDate))}</div></div><div class="cardFoot"><span>Owner: ${esc(o.owner||'Unassigned')}</span><span>Updated ${esc(fmtDT(o.updatedAt))}</span></div></article>`).join('');$('opTable').innerHTML=d.map(o=>`<tr><td><strong>${esc(o.company)}</strong></td><td>${esc(contactName(o.contactId))}</td><td>${esc(o.side)}</td><td>${esc(o.stage)}</td><td>${esc(o.owner)}</td><td>${esc(o.size||'—')}</td><td>${esc(o.next||'—')}</td><td><button class="openLink" data-open="${o.id}">Open</button></td></tr>`).join('');bindOpen()}
function renderNext(){$('nextBoard').innerHTML=roleData().filter(o=>o.next).map(o=>`<article class="nextRow"><div><h3>${esc(contactName(o.contactId))}</h3><p>${esc(o.company)} · ${esc(o.side)}</p></div><div class="nextMain">${esc(o.next)}</div><div class="nextMeta2"><strong>${esc(o.nextOwner||o.owner||'Unassigned')}</strong><br>Action owner</div><div class="nextMeta2"><strong>${esc(fmtDate(o.dueDate))}</strong><br>Due date</div><button class="ghost" data-open="${o.id}">Open</button></article>`).join('');bindOpen()}
function renderPeople(){$('peopleGrid').innerHTML=state.people.map(p=>{const ops=state.opportunities.filter(o=>o.contactId===p.id);return`<article class="personCard"><div class="personTop"><div><div class="personName">${esc(p.name)}</div><div class="cardSub">${esc(p.type||'Relationship not specified')} · ${esc(p.side||'')}</div></div><label class="linkedinCheck"><input type="checkbox" data-linkedin="${p.id}" ${p.hasLinkedIn?'checked':''}> LinkedIn access</label></div><div class="personSection"><label>THESIS</label><textarea data-thesis="${p.id}">${esc(p.thesis)}</textarea></div><div class="personOps">${ops.map(o=>`<div class="miniOp"><div><strong>${esc(o.company)}</strong><br><span>${esc(o.stage)}</span></div><button class="openLink" data-open="${o.id}">Open</button></div>`).join('')}</div><div style="text-align:right;margin-top:12px"><button class="ghost" data-edit-person="${p.id}">Edit person</button></div></article>`}).join('');document.querySelectorAll('[data-linkedin]').forEach(x=>x.onchange=async()=>{await sb.from('people').update({has_linkedin:x.checked}).eq('id',x.dataset.linkedin);await loadData()});document.querySelectorAll('[data-thesis]').forEach(x=>x.onchange=async()=>{await sb.from('people').update({thesis:x.value}).eq('id',x.dataset.thesis)});document.querySelectorAll('[data-edit-person]').forEach(x=>x.onclick=()=>openPersonModal(x.dataset.editPerson));bindOpen()}
function renderAll(){$('navOps').textContent=roleData().length;$('navNext').textContent=roleData().filter(o=>o.next).length;$('navPeople').textContent=state.people.length;populateFilters();renderDashboard();renderOps();renderNext();renderPeople()}
function bindOpen(){document.querySelectorAll('[data-open]').forEach(x=>x.onclick=e=>{e.stopPropagation();openDetail(x.dataset.open)})}
function openDetail(id){const o=state.opportunities.find(x=>x.id===id);if(!o)return;selectedId=id;const p=person(o.contactId);$('detailEyebrow').textContent=`${o.side} · ${o.stage}`;$('detailTitle').textContent=o.company;$('drawerBody').innerHTML=`<section class="detailSec"><div class="detailTitle">CONTACT</div><div class="detailGrid"><div class="detailItem"><div class="l">Person</div><div class="v">${esc(p?.name||'Unassigned')}</div></div><div class="detailItem"><div class="l">Relationship</div><div class="v">${esc(p?.type||'Not specified')}</div></div><div class="detailItem"><div class="l">LinkedIn Access</div><div class="v">${p?.hasLinkedIn?'Yes':'No'}</div></div><div class="detailItem"><div class="l">Thesis</div><div class="v">${esc(p?.thesis||'Not collected yet')}</div></div></div></section><section class="detailSec"><div class="detailTitle">OPPORTUNITY</div><div class="detailGrid"><div class="detailItem"><div class="l">Owner</div><div class="v">${esc(o.owner||'Unassigned')}</div></div><div class="detailItem"><div class="l">Priority</div><div class="v">${esc(o.priority)}</div></div><div class="detailItem"><div class="l">Size</div><div class="v">${esc(o.size||'Not specified')}</div></div><div class="detailItem"><div class="l">Sector / Type</div><div class="v">${esc(o.sector||'Not specified')}</div></div></div></section><section class="detailSec"><div class="detailTitle">NEXT STEP</div><div class="nextBox"><div class="nextCopy">${esc(o.next||'No next step assigned')}</div></div></section><section class="detailSec"><div class="detailTitle">NOTES</div><div>${esc(o.notes||'No notes.')}</div></section>`;$('overlay').classList.remove('hidden');$('drawer').classList.remove('hidden')}
function closeDetail(){$('overlay').classList.add('hidden');$('drawer').classList.add('hidden');selectedId=null}
function fillContact(selected=''){$('contactInput').innerHTML='<option value="">Unassigned</option>'+state.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('contactInput').value=selected}
function openOppModal(id=null){$('oppForm').reset();$('editId').value='';$('editStage').innerHTML=STAGES.map(s=>`<option>${s}</option>`).join('');fillContact();$('oppModalTitle').textContent=id?'Edit Opportunity':'Add Opportunity';if(id){const o=state.opportunities.find(x=>x.id===id);$('editId').value=id;fillContact(o.contactId);$('companyInput').value=o.company;$('editSide').value=o.side;$('ownerInput').value=o.owner;$('editStage').value=o.stage;$('priorityInput').value=o.priority;$('sizeInput').value=o.size;$('sectorInput').value=o.sector;$('nextInput').value=o.next;$('nextOwnerInput').value=o.nextOwner;$('dueDateInput').value=o.dueDate;$('notesInput').value=o.notes}$('oppModal').classList.remove('hidden')}
async function saveOpp(e){e.preventDefault();const id=$('editId').value||null,p={person_id:$('contactInput').value||null,title:$('companyInput').value.trim(),side:$('editSide').value,owner_name:$('ownerInput').value.trim(),stage:$('editStage').value,priority:$('priorityInput').value,opportunity_size:$('sizeInput').value.trim(),sector:$('sectorInput').value.trim(),next_step:$('nextInput').value.trim(),next_step_owner:$('nextOwnerInput').value.trim(),due_date:$('dueDateInput').value||null,notes:$('notesInput').value.trim(),created_by:currentUser.id};const res=id?await sb.from('opportunities').update(p).eq('id',id):await sb.from('opportunities').insert(p);if(res.error){alert(res.error.message);return}$('oppModal').classList.add('hidden');closeDetail();await loadData()}
function openPersonModal(id=null){$('personForm').reset();$('personEditId').value='';$('personModalTitle').textContent=id?'Edit Person':'Add Person';if(id){const p=person(id);$('personEditId').value=id;$('personNameInput').value=p.name;$('personTypeInput').value=p.type;$('personSideInput').value=p.side;$('personLinkedInInput').value=String(p.hasLinkedIn);$('personThesisInput').value=p.thesis;$('personNotesInput').value=p.notes}$('personModal').classList.remove('hidden')}
async function savePerson(e){e.preventDefault();const id=$('personEditId').value||null,p={name:$('personNameInput').value.trim(),relationship_type:$('personTypeInput').value.trim(),primary_side:$('personSideInput').value,has_linkedin:$('personLinkedInInput').value==='true',thesis:$('personThesisInput').value.trim(),notes:$('personNotesInput').value.trim(),created_by:currentUser.id};const res=id?await sb.from('people').update(p).eq('id',id):await sb.from('people').insert(p);if(res.error){alert(res.error.message);return}$('personModal').classList.add('hidden');await loadData()}
function parseEntry(e){const side=/\b(buyside|buy side|buy-side)\b/i.test(e)?'Buy Side':'Sell Side',nm=e.match(/^\s*([A-Z][A-Za-z'’.-]+(?:\s+[A-Z][A-Za-z'’.-]+){0,2})\s*,/),name=nm?nm[1]:e.split(',')[0],sm=e.match(/\$\s?\d+(?:\.\d+)?\s?(?:billion|million|bn|mm|m|b)\b/i),next=(e.match(/next steps?\s*(?:are|is|:|-)?\s*([^.;]+)/i)||[])[1]||'',type=/family office/i.test(e)?'Family Office':/\bIB\b|investment banker/i.test(e)?'Investment Banker':side==='Buy Side'?'Buy-side Relationship':'Sell-side Relationship';return{name:name.trim(),side,size:sm?.[0]||'',next,type,raw:e}}
function parseAI(){return $('aiInput').value.split(/\n+|;\s*/).map(x=>x.trim()).filter(Boolean).map(parseEntry)}
function previewAI(){$('aiPreview').innerHTML=parseAI().map(x=>`<div class="previewItem"><div class="previewName">${esc(x.name)}</div><div class="previewMeta">${esc(x.side)} · ${esc(x.type)} · ${esc(x.size)}</div><div class="previewNext">Next: ${esc(x.next||'No next step detected')}</div></div>`).join('')}
async function addAI(){for(const x of parseAI()){let p=state.people.find(p=>p.name.toLowerCase()===x.name.toLowerCase());if(!p){const {data,error}=await sb.from('people').insert({name:x.name,relationship_type:x.type,primary_side:x.side,created_by:currentUser.id}).select().single();if(error)continue;p=mapPerson(data)}await sb.from('opportunities').insert({person_id:p.id,title:x.side==='Buy Side'?`${x.name} Buy-side Relationship`:`${x.name} Sell-side Opportunities`,side:x.side,owner_name:'Chase',stage:'New',priority:'Medium',opportunity_size:x.size,sector:x.type,next_step:x.next,next_step_owner:'Chase',notes:x.raw,created_by:currentUser.id})}$('aiInput').value='';$('aiPreview').innerHTML='';await loadData()}
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.navBtn').forEach(x=>x.classList.remove('active'));$(v+'View').classList.add('active');document.querySelector(`.navBtn[data-view="${v}"]`).classList.add('active');const labels={dashboard:['Dashboard','See every active opportunity and what needs to happen next.'],opportunities:['Opportunities','Manage sell-side opportunities and buy-side relationships in one place.'],nextsteps:['Next Steps','Keep every relationship moving with a clear next action.'],people:['People & Theses','Track each relationship, their thesis, and LinkedIn access.'],ai:['AI Quick Add','Paste raw deal notes and turn them into structured opportunities.']};$('pageTitle').textContent=labels[v][0];$('pageSub').textContent=labels[v][1]}
async function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='outerhaven-data.json';a.click();URL.revokeObjectURL(u)}
async function handleAuth(){const {data:{session}}=await sb.auth.getSession();if(session){if(!(await allowed(session.user.email))){await sb.auth.signOut();showAuth('This email is not approved for the dashboard.');return}currentUser=session.user;$('signedInEmail').textContent=session.user.email;$('authGate').classList.add('hidden');$('loadingScreen').classList.add('hidden');await loadData();subscribe();return}showAuth('')}
function showAuth(msg){$('loadingScreen').classList.add('hidden');$('authGate').classList.remove('hidden');$('authMsg').textContent=msg}
function subscribe(){sb.channel('outerhaven-live').on('postgres_changes',{event:'*',schema:'public',table:'people'},loadData).on('postgres_changes',{event:'*',schema:'public',table:'opportunities'},loadData).subscribe()}
document.addEventListener('DOMContentLoaded',()=>{$('authForm').onsubmit=async e=>{e.preventDefault();const email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value;if(!(await allowed(email))){$('authMsg').textContent='This email is not on the approved access list.';return}const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('authMsg').textContent=error.message;return}await handleAuth()};$('signUpBtn').onclick=async()=>{const email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value;if(!(await allowed(email))){$('authMsg').textContent='This email is not on the approved access list.';return}const {error}=await sb.auth.signUp({email,password,options:{data:{full_name:email.startsWith('chase')?'Chase Hamby':'Tengku'}}});$('authMsg').textContent=error?error.message:'Account created. Check your email if Supabase asks you to confirm it, then sign in.'};$('signOutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};document.querySelectorAll('.navBtn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));$('addOppBtn').onclick=()=>openOppModal();$('addPersonBtn').onclick=()=>openPersonModal();$('addPersonBtn2').onclick=()=>openPersonModal();$('closeDrawer').onclick=closeDetail;$('overlay').onclick=closeDetail;$('editOpp').onclick=()=>{const id=selectedId;closeDetail();openOppModal(id)};$('deleteOpp').onclick=async()=>{if(selectedId&&confirm('Delete this opportunity?')){await sb.from('opportunities').delete().eq('id',selectedId);closeDetail();await loadData()}};$('closeOppModal').onclick=()=>$('oppModal').classList.add('hidden');$('cancelOpp').onclick=()=>$('oppModal').classList.add('hidden');$('oppForm').onsubmit=saveOpp;$('closePersonModal').onclick=()=>$('personModal').classList.add('hidden');$('cancelPerson').onclick=()=>$('personModal').classList.add('hidden');$('personForm').onsubmit=savePerson;['searchInput','sideFilter','stageFilter','ownerFilter','priorityFilter'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',renderOps));$('roleFilter').onchange=renderAll;document.querySelectorAll('.segment').forEach(b=>b.onclick=()=>{document.querySelectorAll('.segment').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('opCards').classList.toggle('hidden',b.dataset.layout!=='cards');$('opTableWrap').classList.toggle('hidden',b.dataset.layout!=='table')});$('previewAiBtn').onclick=previewAI;$('addAiBtn').onclick=addAI;$('exportBtn').onclick=exportData;handleAuth()});